spring.application.name=movilidadMDQ
spring.config.import=optional:file:.env[.properties]
app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS}
# Configuracion BDD
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
#APIs Keys
# Google Maps
google.maps.api.key=${GOOGLE_MAPS_KEY}
# OpenWeather
openweather.api.key=${WEATHER_API_KEY}

# OpenAPI / Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs




# SPRING SECURITY
# Configuracion JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
# OAuth2 Google
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_OAUTH_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_OAUTH_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile,email
